name: Daily Market Report Generation

on:
  schedule:
    # 매일 한국 시간 오후 5시 (UTC 08:00)에 실행 
    - cron: '0 8 * * 1-5'  # 평일에만 실행
  
  # 수동 실행 옵션 추가
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Chrome 설치
    - name: Install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
 
    # Chrome Driver 설치
    - name: Install Chrome Driver
      uses: nanasess/setup-chromedriver@master
 
    # 가상 디스플레이 설정
    - name: Setup virtual display
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
 
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-nanum
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate market report
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        FREDAPI_KEY: ${{ secrets.FREDAPI_KEY }}
      run: |
        # Chrome 및 Chromedriver 버전 확인
        google-chrome --version
        chromedriver --version
        # 리포트 생성
        python -m src.report_generator

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add reports/
        git add logs/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update market report: $(date +'%Y-%m-%d')" && git push https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git)

    - name: Upload report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: market-report
        path: reports/
        retention-days: 7

    # 에러 발생 시 이슈 생성
    - name: Error notification
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Market Report Generation Failed: ${new Date().toISOString()}`,
            body: `Workflow run failed: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}\nPossible Chrome/Selenium related issues - please check logs.`
          })